# You can use the player placeholder %player% in the round and game finish commands!
round-finish-commands:
  taggers:
  #  - eco add %player% 10
  survivors:
  # - eco add %player% 20

arena-finish-commands:
  #- eco add %winner% 1000

# This will result in:
# 1. Players instantly joining TNT-Tag once they get into the server.
# 2. Players being unable to leave TNT-Tag, they will instead be connected to your lobby server once they try to leave.

bungee-mode:
  enabled: false
  lobby-server: "lobby" # The name of your lobby server.

# Set to true if you want to use the percentage, set it to false if you only want one tagger.
use-taggers-percentage: true

# The amount of people that will be the tagger in a round.
taggers-percentage: "40%"

timesToBroadcast:
  - 50
  - 40
  - 30
  - 20
  - 15
  - 10
  - 5
  - 4
  - 3
  - 2
  - 1

startMessage:
  - "&b==================&cTNT-Tag&b=================="
  - "                    &6&lTNT-Tag        "
  - "   &6You need to avoid the tagger and run fast!        "
  - " &6&lHit someone quickly when you get tagged before you explode!        "
  - "&b==================&cTNT-Tag&b=================="

# Determines the number of players left in the arena to trigger teleportation to the start location at each round.
player-teleport-threshold: 5

# If everyone can hit each other in the game, this can be a fun thing that also prevents people from camping in one place.
game-combat: true