name: Tnttag
version: 6.6
main: nl.juriantech.tnttag.Tnttag
softdepend: [PlaceholderAPI, PartyAndFriends]
api-version: 1.13
authors: [ Jurian ]
description: A TNT-Tag minigame!
website: juriantech.nl
